export const lng = {
    "ru": {
        "common": {
            "step": "Шаг",
            "btnPrev": "Назад",
            "btnNext": "Вперёд",
            "btnOrderAndPay": "Zahlungspflichtig buchen",
            "btnCommitOrder": "Подать заявку на визу",
            "btnSaveOrder": "Сохранить заявку",
            "confirmResetText": "Внимание, выбор услуги и допуслуг будет сброшен, продолжить?",
            "btnYes": "Да",
            "btnNo": "Нет",
        },
        "step1": {
            "crumb": "Buchungsauftrag",
            "header": "Buchungsauftrag",
            "countryLabel": "Выберите страну назначения:",
            "countryPlaceholder": "Выберите",
            "serviceGrpLabel": "Выберите группу:",
            "serviceLabel": "Выберите подтип визы:"
        },
        "step2": {
            "crumb": "Aufenthaltsdauer",
            "header": "Расчет примерной стоимости для одного человека",
            "processingText": "<b>СРОК ОБРАБОТКИ</b> статический текст is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            "btnInfo": "Инфо-кнопка",
            "modalInfoHeader": "Информация",
            "nationalitiesLabel": "Гражданство:",
            "nationalitiesPlaceholder": "Выберите",
            "residenceRegionsLabel": "Место жительства:",
            "residenceRegionsPlaceholder": "Выберите",
            "processingDuration": "Bearbeitungszeit",
            "dimension": {
                "h": "Stunden",
                "d": "Werktage",
                "m": "Monat"
            },
            "multiplicity": "malige Einreise",
            "order": "Kaufen",
            "included": "В стоимость входит: <b>консульский сбор, сервисный сбор, сбор за приглашение</b>"
        },
        "step3": {
            "crumb": "Заполнение данных о туристах",
            "header": "Заполнение данных",
            "participant": "Участник",
            "gender": {
                "male": "Herr",
                "female": "Frau"
            },
            "btnDelete": "Удалить",
            "name": "Имя",
            "sname": "Фамилия",
            "nationality": "Гражданство",
            "residenceRegions": "Место жительства",
            "discount": "Скидка",
            "birthDate": "Дата рождения",
            "btnAdd": "Добавить туриста"
        },
        "step4": {
            "crumb": "Дополнительные услуги",
            "header": "Дополнительные услуги",
            "perPerson": "pro Person",
            "included": "включено",
            "added": "добавлено",
            "add": "добавить",
            "select": "Выбрать"
        },
        "step5": {
            "crumb": "Информация о заказчике",
            "header": "Информация о заказчике",
            "company": "Фирма",
            "companyName": "Название фирмы",
            "gender": {
                "male": "Herr",
                "female": "Frau"
            },
            "name": "Имя",
            "sname": "Фамилия",
            "address": "Адрес",
            "zip": "Индекс",
            "city": "Город",
            "country": "Страна",
            "tel": "Телефон",
            "ifThereIs": "(если есть)",
            "mobile": "Мобильный телефон",
            "email": "email",
            "deliveryAddress": "Lieferanschrift",
            "addressCorresponds": "Lieferanschrift entspricht Auftraggeber",
            "addressDifferent": "abweichende Lieferanschrift",
            "pickUp": "Abholen",
            "workingTime": "Время работы:",
            "deliveryByEmail": "Документы будут доставлены на электронный адрес клиента"
        },
        "step6": {
            "crumb": "Способ отправки",
            "header": "Способ отправки",
        },
        "step7": {
            "crumb": "Проверка данных",
            "header": "Проверка данных",
            "country": "Страна",
            "duration": "Срок визы:",
            "serviceGrp": "Тип визы:",
            "multiplicity": "Кратность:",
            "service": "Подтип визы:",
            "processingDuration": "Срок обработки:",
            "nameSurname": "Имя, фамилия",
            "nationality": "Гражданство",
            "location": "Проживание",
            "additionally": "Дополнительно",
            "servicePackage": "Сервис пакет:",
            "suppServices": "Дополнительные услуги:",
            "delivery": "Способ доставки:",
            "amount": "Preis Total:",
            "more": "Подробнее",
            "clientInfo": "Информация о клиенте",
            "address": "Адрес доставки",
            "pickUp": "Самовывоз из",
            "termsAndConditions": "Allgemeine Geschäftsbedingungen",
            "paymentTerms": "Zahlungsbedingungen",
            "cancellationPolicy": "Stornobedingungen",
            "termsText": "Mit dem erfolgreichen Abschluss Ihrer Buchung kommt ein Vertrag mit dem Anbieter zustande. Die Bestätigung und Rechnung zu Ihrer Buchung werden Ihnen dann von HomeToGo und/oder dem Anbieter zugesandt. Durch Klicken auf \"Zahlungspflichtig buchen\" akzeptieren Sie die AGB des Anbieters und die AGB der HomeToGo GmbH. Weitere Informationen zur Verarbeitung Ihrer Daten finden Sie in unserer Datenschutzerklärung.",

        },
        "step8": {
            "crumb": "Способ оплаты",
            "header": "Способ оплаты",
        },
        "success": {
            "thanks": "спасибо",
            "forOrder": "за Вашу заявку",
            "yourOrder": "Ваша заявка",
            "orderProcessing": "принята в обработку, мы свяжемся с Вами в ближайшее время!",
            "statusText": "Статус заказа можно отследить в",
            "cabinet": "Личном кабинете",
            "bottomText": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur commodi ipsam natus earum id fuga esse deleniti soluta assumenda libero, doloribus, molestiae explicabo accusamus quasi impedit asperiores aperiam placeat accusantium."
        }
    },

    "en": {
        "common": {
            "step": "Step",
            "btnPrev": "Prev",
            "btnNext": "Next",
            "btnOrderAndPay": "Zahlungspflichtig buchen",
            "btnCommitOrder": "Подать заявку на визу",
            "btnSaveOrder": "Сохранить заявку",
            "confirmResetText": "Внимание, выбор услуги и допуслуг будет сброшен, продолжить?",
            "btnYes": "Да",
            "btnNo": "Нет",
        },
        "step1": {
            "crumb": "Buchungsauftrag",
            "header": "Buchungsauftrag",
            "countryLabel": "Выберите страну назначения:",
            "countryPlaceholder": "Выберите",
            "serviceGrpLabel": "Выберите группу:",
            "serviceLabel": "Выберите подтип визы:"
        },
        "step2": {
            "crumb": "Aufenthaltsdauer",
            "header": "Расчет примерной стоимости для одного человека",
            "processingText": "<b>СРОК ОБРАБОТКИ</b> статический текст is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            "btnInfo": "Инфо-кнопка",
            "modalInfoHeader": "Информация",
            "nationalitiesLabel": "Гражданство:",
            "nationalitiesPlaceholder": "Выберите",
            "residenceRegionsLabel": "Место жительства:",
            "residenceRegionsPlaceholder": "Выберите",
            "processingDuration": "Bearbeitungszeit",
            "dimension": {
                "h": "Stunden",
                "d": "Werktage",
                "m": "Monat"
            },
            "multiplicity": "malige Einreise",
            "order": "Kaufen",
            "included": "В стоимость входит: <b>консульский сбор, сервисный сбор, сбор за приглашение</b>"
        },
        "step3": {
            "crumb": "Заполнение данных о туристах",
            "header": "Заполнение данных",
            "participant": "Участник",
            "gender": {
                "male": "Herr",
                "female": "Frau"
            },
            "btnDelete": "Удалить",
            "name": "Имя",
            "sname": "Фамилия",
            "nationality": "Гражданство",
            "residenceRegions": "Место жительства",
            "discount": "Скидка",
            "birthDate": "Дата рождения",
            "btnAdd": "Добавить туриста"
        },
        "step4": {
            "crumb": "Дополнительные услуги",
            "header": "Дополнительные услуги",
            "perPerson": "pro Person",
            "included": "включено",
            "added": "добавлено",
            "add": "добавить",
            "select": "Выбрать"
        },
        "step5": {
            "crumb": "Информация о заказчике",
            "header": "Информация о заказчике",
            "company": "Фирма",
            "companyName": "Название фирмы",
            "gender": {
                "male": "Herr",
                "female": "Frau"
            },
            "name": "Имя",
            "sname": "Фамилия",
            "address": "Адрес",
            "zip": "Индекс",
            "city": "Город",
            "country": "Страна",
            "tel": "Телефон",
            "ifThereIs": "(если есть)",
            "mobile": "Мобильный телефон",
            "email": "email",
            "deliveryAddress": "Lieferanschrift",
            "addressCorresponds": "Lieferanschrift entspricht Auftraggeber",
            "addressDifferent": "abweichende Lieferanschrift",
            "pickUp": "Abholen",
            "workingTime": "Время работы:",
            "deliveryByEmail": "Документы будут доставлены на электронный адрес клиента"
        },
        "step6": {
            "crumb": "Способ отправки",
            "header": "Способ отправки",
        },
        "step7": {
            "crumb": "Проверка данных",
            "header": "Проверка данных",
            "country": "Страна",
            "duration": "Срок визы:",
            "serviceGrp": "Тип визы:",
            "multiplicity": "Кратность:",
            "service": "Подтип визы:",
            "processingDuration": "Срок обработки:",
            "nameSurname": "Имя, фамилия",
            "nationality": "Гражданство",
            "location": "Проживание",
            "additionally": "Дополнительно",
            "servicePackage": "Сервис пакет:",
            "suppServices": "Дополнительные услуги:",
            "delivery": "Способ доставки:",
            "amount": "Preis Total:",
            "more": "Подробнее",
            "clientInfo": "Информация о клиенте",
            "address": "Адрес доставки",
            "pickUp": "Самовывоз из",
            "termsAndConditions": "Allgemeine Geschäftsbedingungen",
            "paymentTerms": "Zahlungsbedingungen",
            "cancellationPolicy": "Stornobedingungen",
            "termsText": "Mit dem erfolgreichen Abschluss Ihrer Buchung kommt ein Vertrag mit dem Anbieter zustande. Die Bestätigung und Rechnung zu Ihrer Buchung werden Ihnen dann von HomeToGo und/oder dem Anbieter zugesandt. Durch Klicken auf \"Zahlungspflichtig buchen\" akzeptieren Sie die AGB des Anbieters und die AGB der HomeToGo GmbH. Weitere Informationen zur Verarbeitung Ihrer Daten finden Sie in unserer Datenschutzerklärung.",

        },
        "step8": {
            "crumb": "Способ оплаты",
            "header": "Способ оплаты",
        },
        "success": {
            "thanks": "спасибо",
            "forOrder": "за Вашу заявку",
            "yourOrder": "Ваша заявка",
            "orderProcessing": "принята в обработку, мы свяжемся с Вами в ближайшее время!",
            "statusText": "Статус заказа можно отследить в",
            "cabinet": "Личном кабинете",
            "bottomText": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur commodi ipsam natus earum id fuga esse deleniti soluta assumenda libero, doloribus, molestiae explicabo accusamus quasi impedit asperiores aperiam placeat accusantium."
        }
    },
}
